version: "3"

services:
  tasksapi:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - dbnetwork
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: 
    networks:
      - dbnetwork

networks:
  dbnetwork:
    driver: bridge

